In [2]:
import json
from xtalpaint.inpainting.config_schema import XtalPaintConfig
from xtalpaint.utils.relaxation_utils import relax_structures
from ase.io import read
from pymatgen.io.ase import AseAtomsAdaptor
from IPython.display import clear_output

In [3]:
input_structures = read("test-structures.extxyz", index=':')
input_structures = {
    a.info['uuid'].replace("-", "_"): AseAtomsAdaptor.get_structure(a) for a in input_structures
}

In [4]:
len(input_structures)

5

In [5]:
param_grid = {
    "N_steps": 5,
    "coordinates_snr": 0.2,
    "n_corrector_steps": 1,
    "batch_size": 1000,
}

In [6]:
inputs = XtalPaintConfig(
    candidate_generation={
        "n_inp": {
            k.replace("-", "_"): int(s.composition["H"])
            for k, s in input_structures.items()
        },
        "element": "H",
        "num_samples": 1,
    },
    inpainting={
        "record_trajectories": False,
        "predictor_corrector": "baseline",
        **param_grid,
        "pretrained_name": "mattergen_base",
        "sampling_config_path": "../mattergen-configs/sampling_conf",
    },
    relaxation={
        "constrained": True,
        "full": True,
        "relax_config": {
            "params": {
                "mlip": "mattersim",
                "optimizer": "BFGS",
                "load_path": "MatterSim-v1.0.0-5M.pth",
                "fmax": 0.01,
                "max_n_steps": 50,
                "max_natoms_per_batch": 5000,
                "device": "cpu",
                "elements_to_relax": ["H"],
                "return_initial_energies": False,
                "return_initial_forces": False,
                "return_final_forces": False,
            },
            "aiida": None,
        },
    },
)

/Users/treents/project/paper-missing-hydrogen-archive/git/XtalPaint-dev/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

MODELS_PROJECT_ROOT: /Users/treents/project/paper-missing-hydrogen-archive/git/XtalPaint-dev/.venv/lib/python3.10/site-packages/mattergen

/Users/treents/project/paper-missing-hydrogen-archive/git/XtalPaint-dev/.venv/lib/python3.10/site-packages/lightning_fabric/__init__.py:36: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  __import__("pkg_resources").declare_namespace(__name__)

## Running the inpainting workflow without AiiDA

In [7]:
print(f"Processing {len(input_structures)} structures")

Processing 5 structures

## Generate inpainting candidates

In [8]:
from xtalpaint.inpainting.generate_candidates import (
    generate_inpainting_candidates,
)

In [9]:
# Step 1: Generate inpainting candidates
print("Running inpainting pipeline...")

n_inp_dict = inputs.candidate_generation.n_inp
element = inputs.candidate_generation.element
num_samples = inputs.candidate_generation.num_samples

inpainting_candidates = generate_inpainting_candidates(
    structures=input_structures,
    n_inp=n_inp_dict,
    element=element,
    num_samples=num_samples,
)

print(f"Generated {len(inpainting_candidates)} inpainted structures")

Running inpainting pipeline...
Generated 5 inpainted structures

In [10]:
inpainting_candidates

{'20acc66e_8e38_4e5e_9e7a_c2400262cdc8': Structure Summary
 Lattice
     abc : 5.169783747 5.169783747 5.169783747
  angles : 90.0 90.0 90.0
  volume : 138.17107311088554
       A : 5.169783747 0.0 0.0
       B : 0.0 5.169783747 0.0
       C : 0.0 0.0 5.169783747
     pbc : True True True
 PeriodicSite: N (2.309, 4.894, 2.86) [0.4467, 0.9467, 0.5533]
 PeriodicSite: N (4.894, 2.86, 2.309) [0.9467, 0.5533, 0.4467]
 PeriodicSite: N (2.86, 2.309, 4.894) [0.5533, 0.4467, 0.9467]
 PeriodicSite: N (0.2756, 0.2756, 0.2756) [0.0533, 0.0533, 0.0533]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan],
 '47b9a869_9b1e_438b_8c93_f5ac654bfdd8': Structure Summary
 Lattice
     abc : 4.401448665821795 4.401448665821795 7.1759779644947
  angles : 90.0 90.0 120.19000916247398
  volume : 120.16231769034825
       A : 2.1944008576909 -3.8154102313683 0.0
       B : 2.1944008576909 3.8154102313683 0.0
       C : 0.0 0.0 7.1759779644947
     pbc : True True True
 PeriodicSite: O (2.194, 2.549, 3.886) [0.1659, 0.8341, 0.5415]
 PeriodicSite: O (7.744e-18, 1.266, 0.2978) [-0.1659, 0.1659, 0.0415]
 PeriodicSite: O (2.194, 2.544, 6.579) [0.1666, 0.8334, 0.9168]
 PeriodicSite: O (1.254e-17, 1.272, 2.991) [-0.1666, 0.1666, 0.4168]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan],
 '662c7351_ee76_48ea_bab7_b733e1fdf607': Structure Summary
 Lattice
     abc : 8.414296245395509 8.414296245395509 8.414296245395509
  angles : 93.51670444494472 93.51670444494472 151.32085705391836
  volume : 276.98877799736266
       A : -5.7644391936362 5.7644391936362 2.0839536633569
       B : 5.7644391936362 -5.7644391936362 2.0839536633569
       C : 5.7644391936362 5.7644391936362 -2.0839536633569
     pbc : True True True
 PeriodicSite: O (4.413e-16, 8.82, -0.1928) [0.7188, -0.04627, 0.7651]
 PeriodicSite: O (7.374e-16, 3.056, 1.235) [0.5613, 0.2963, 0.2651]
 PeriodicSite: O (2.987e-16, 2.709, -0.1928) [0.1887, -0.04627, 0.2349]
 PeriodicSite: O (7.102e-16, 8.473, 1.235) [1.031, 0.2963, 0.7349]
 PeriodicSite: O (3.056, 5.764, 2.277) [1.046, 0.8113, 0.7651]
 PeriodicSite: O (8.82, 5.764, 0.8491) [0.7037, 0.9688, 1.265]
 PeriodicSite: O (8.473, 5.764, 2.277) [1.046, 1.281, 1.235]
 PeriodicSite: O (2.709, 5.764, 0.8491) [0.7037, 0.4387, 0.7349]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan],
 '7fa282c5_4971_46f4_8b3b_776595a0fa06': Structure Summary
 Lattice
     abc : 6.3321144796 6.332114479595774 6.603633127
  angles : 90.0 90.0 120.00000000002208
  volume : 229.3037119499634
       A : 6.3321144796 0.0 0.0
       B : -3.1660572398 5.483771999 0.0
       C : 0.0 0.0 6.603633127
     pbc : True True True
 PeriodicSite: Y (2.099, 3.636, 1.651) [0.6631, 0.6631, 0.25]
 PeriodicSite: Y (4.199, 0.0, 4.953) [0.6631, 0.0, 0.75]
 PeriodicSite: Y (-2.099, 3.636, 4.953) [-6.806e-10, 0.6631, 0.75]
 PeriodicSite: Y (-1.067, 1.848, 1.651) [7.402e-10, 0.3369, 0.25]
 PeriodicSite: Y (1.067, 1.848, 4.953) [0.3369, 0.3369, 0.75]
 PeriodicSite: Y (2.134, 0.0, 1.651) [0.3369, 0.0, 0.25]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan],
 'c436bbf4_9aef_44a8_8960_00227f79a32f': Structure Summary
 Lattice
     abc : 4.9620535714985 5.689428317103 4.4034011624103
  angles : 90.0 90.0 90.0
  volume : 124.31351070276466
       A : 4.9620535714985 0.0 0.0
       B : 0.0 5.689428317103 0.0
       C : 0.0 0.0 4.4034011624103
     pbc : True True True
 PeriodicSite: V (2.481, 1.451, 2.02) [0.5, 0.2551, 0.4587]
 PeriodicSite: V (-2.13e-06, 4.238, 2.02) [-4.293e-07, 0.7449, 0.4587]
 PeriodicSite: V (2.481, 4.238, 2.02) [0.5, 0.7449, 0.4587]
 PeriodicSite: V (2.13e-06, 1.451, 2.02) [4.293e-07, 0.2551, 0.4587]
 PeriodicSite: V (2.481, 2.845, -0.1521) [0.5, 0.5, -0.03455]
 PeriodicSite: V (0.0, 2.845, -0.1521) [0.0, 0.5, -0.03455]
 PeriodicSite: V (2.481, 0.0, -0.1605) [0.5, 0.0, -0.03644]
 PeriodicSite: V (0.0, 0.0, -0.1605) [0.0, 0.0, -0.03644]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]
 PeriodicSite: H (nan, nan, nan) [nan, nan, nan]}

## Run inpainting

In [11]:
from xtalpaint.inpainting.inpainting_process import (
    run_inpainting_pipeline,
    run_mpi_parallel_inpainting_pipeline,
)

In [12]:
USE_MPI_FOR_PARALLEL_INPAINTING = False

inpainting_method = (
    run_mpi_parallel_inpainting_pipeline
    if USE_MPI_FOR_PARALLEL_INPAINTING
    else run_inpainting_pipeline
)

In [13]:
config = inputs.inpainting.model_dump(exclude_none=True)

inpainting_outputs = run_inpainting_pipeline(
    structures=inpainting_candidates, config=config
)

clear_output()

In [14]:
inpainting_outputs['structures'].get_structures(strct_type='pymatgen')

{'20acc66e_8e38_4e5e_9e7a_c2400262cdc8': Structure Summary
 Lattice
     abc : 5.1697835922241255 5.1697835922241255 5.169783592224121
  angles : 90.00000250447799 90.00000250447799 90.00000250447816
  volume : 138.171060700957
       A : 5.169783592224121 0.0 -2.2597841109472938e-07
       B : -2.2597843664143413e-07 5.169783592224116 -2.2597841109472938e-07
       C : 0.0 0.0 5.169783592224121
     pbc : True True True
 PeriodicSite: N (2.309, 4.894, 2.86) [0.4467, 0.9467, 0.5533]
 PeriodicSite: N (4.894, 2.86, 2.309) [0.9467, 0.5533, 0.4467]
 PeriodicSite: N (2.86, 2.309, 4.894) [0.5533, 0.4467, 0.9467]
 PeriodicSite: N (0.2756, 0.2756, 0.2756) [0.0533, 0.0533, 0.0533]
 PeriodicSite: H (1.14, 4.434, 0.5381) [0.2206, 0.8578, 0.1041]
 PeriodicSite: H (1.937, 1.15, 4.583) [0.3747, 0.2224, 0.8865]
 PeriodicSite: H (1.436, 4.945, 2.987) [0.2778, 0.9566, 0.5778]
 PeriodicSite: H (3.769, 2.298, 0.758) [0.729, 0.4444, 0.1466]
 PeriodicSite: H (4.507, 2.123, 4.563) [0.8718, 0.4107, 0.8826]
 PeriodicSite: H (3.157, 0.6855, 2.533) [0.6106, 0.1326, 0.49]
 PeriodicSite: H (3.407, 1.12, 0.2044) [0.659, 0.2167, 0.03953]
 PeriodicSite: H (1.048, 2.116, 3.06) [0.2027, 0.4093, 0.5919]
 PeriodicSite: H (3.138, 3.168, 1.91) [0.607, 0.6127, 0.3694]
 PeriodicSite: H (4.154, 3.005, 3.073) [0.8034, 0.5812, 0.5943]
 PeriodicSite: H (0.1894, 3.669, 2.09) [0.03663, 0.7097, 0.4043]
 PeriodicSite: H (0.2451, 3.923, 4.987) [0.04742, 0.7589, 0.9647],
 '47b9a869_9b1e_438b_8c93_f5ac654bfdd8': Structure Summary
 Lattice
     abc : 4.38880300521851 4.401449203491215 7.175978183746338
  angles : 90.00000250447809 90.00000250447802 119.90500920011145
  volume : 120.16235473216483
       A : 4.388803005218506 0.0 -1.9184066957222967e-07
       B : -2.1944020434734735 3.815410169629585 -1.9239345760979631e-07
       C : 0.0 0.0 7.175978183746338
     pbc : True True True
 PeriodicSite: O (2.194, 2.549, 3.886) [0.8341, 0.6681, 0.5415]
 PeriodicSite: O (-4.87e-08, 1.266, 0.2978) [0.1659, 0.3319, 0.0415]
 PeriodicSite: O (2.194, 2.544, 6.579) [0.8334, 0.6667, 0.9168]
 PeriodicSite: O (-3.111e-07, 1.272, 2.991) [0.1666, 0.3333, 0.4168]
 PeriodicSite: H (-1.41, 2.653, 3.074) [0.02646, 0.6955, 0.4283]
 PeriodicSite: H (-0.8308, 2.039, 1.796) [0.07786, 0.5343, 0.2503]
 PeriodicSite: H (2.268, 2.906, 4.844) [0.8975, 0.7616, 0.675]
 PeriodicSite: H (0.8597, 3.518, 3.477) [0.6569, 0.922, 0.4846]
 PeriodicSite: H (-0.516, 1.239, 6.565) [0.04476, 0.3247, 0.9149]
 PeriodicSite: H (1.068, 3.239, 6.799) [0.6679, 0.849, 0.9475]
 PeriodicSite: H (0.3006, 1.175, 4.255) [0.2225, 0.3079, 0.593]
 PeriodicSite: H (0.9108, 0.9392, 0.4745) [0.3306, 0.2462, 0.06613],
 '662c7351_ee76_48ea_bab7_b733e1fdf607': Structure Summary
 Lattice
     abc : 4.167909019574006 8.414296283494188 8.414295196533203
  angles : 86.4832955066596 75.66042236811894 75.66042279114727
  volume : 276.9888425278154
       A : 4.038057327270508 0.0 1.0322589874267578
       B : 2.019028748729142 8.152147915404894 0.5161290764808655
       C : 0.0 0.0 8.414295196533203
     pbc : True True True
 PeriodicSite: O (0.6612, 1.915, 6.606) [0.04627, 0.2349, 0.7651]
 PeriodicSite: O (4.326, 5.991, 3.336) [0.7037, 0.7349, 0.2651]
 PeriodicSite: O (1.732, 6.237, 2.419) [0.04627, 0.7651, 0.2349]
 PeriodicSite: O (3.377, 2.161, 7.047) [0.7037, 0.2651, 0.7349]
 PeriodicSite: O (3.377, 1.915, 2.84) [0.7188, 0.2349, 0.2349]
 PeriodicSite: O (3.751, 5.991, 7.143) [0.5613, 0.7349, 0.7349]
 PeriodicSite: O (2.307, 6.237, 7.027) [0.1887, 0.7651, 0.7651]
 PeriodicSite: O (0.6612, 2.161, 2.399) [0.03121, 0.2651, 0.2651]
 PeriodicSite: H (2.003, 6.885, 7.471) [0.07385, 0.8445, 0.827]
 PeriodicSite: H (4.384, 7.511, 8.59) [0.6251, 0.9214, 0.8877]
 PeriodicSite: H (3.426, 5.829, 2.848) [0.491, 0.715, 0.2343]
 PeriodicSite: H (3.292, 2.8, 3.087) [0.6434, 0.3435, 0.2669]
 PeriodicSite: H (1.211, 2.332, 7.627) [0.1569, 0.2861, 0.8697]
 PeriodicSite: H (1.483, 1.609, 3.175) [0.2686, 0.1974, 0.3322]
 PeriodicSite: H (1.13, 3.42, 5.603) [0.07015, 0.4195, 0.6316]
 PeriodicSite: H (4.362, 6.361, 6.174) [0.6902, 0.7803, 0.6012],
 '7fa282c5_4971_46f4_8b3b_776595a0fa06': Structure Summary
 Lattice
     abc : 6.332112789154059 6.332114219665534 6.603632926940918
  angles : 90.00000250447802 90.00000250447808 120.00000394341146
  volume : 229.3036252628656
       A : 6.332112789154053 0.0 -2.767854425655969e-07
       B : -3.1660574872561824 5.483771555989494 -2.7678549940901576e-07
       C : 0.0 0.0 6.603632926940918
     pbc : True True True
 PeriodicSite: Y (2.134, 0.0, 4.953) [0.3369, 0.0, 0.75]
 PeriodicSite: Y (1.067, 1.848, 1.651) [0.3369, 0.3369, 0.25]
 PeriodicSite: Y (-2.099, 3.636, 1.651) [0.0, 0.6631, 0.25]
 PeriodicSite: Y (-1.067, 1.848, 4.953) [0.0, 0.3369, 0.75]
 PeriodicSite: Y (4.199, 0.0, 1.651) [0.6631, 0.0, 0.25]
 PeriodicSite: Y (2.099, 3.636, 4.953) [0.6631, 0.6631, 0.75]
 PeriodicSite: H (0.794, 2.63, 3.703) [0.3652, 0.4797, 0.5608]
 PeriodicSite: H (1.941, 1.615, 4.938) [0.4539, 0.2946, 0.7478]
 PeriodicSite: H (5.916, 0.1827, 5.518) [0.951, 0.03332, 0.8356]
 PeriodicSite: H (-0.06808, 4.299, 4.622) [0.3812, 0.7839, 0.6999]
 PeriodicSite: H (1.295, 4.365, 0.2861) [0.6025, 0.7961, 0.04332]
 PeriodicSite: H (2.724, 4.428, 2.062) [0.834, 0.8074, 0.3122]
 PeriodicSite: H (3.671, 2.61, 4.224) [0.8177, 0.4759, 0.6396]
 PeriodicSite: H (3.874, 3.342, 6.056) [0.9165, 0.6095, 0.9171]
 PeriodicSite: H (-0.8797, 4.082, 0.5196) [0.2333, 0.7444, 0.07868]
 PeriodicSite: H (4.303, 1.536, 5.382) [0.8195, 0.28, 0.815]
 PeriodicSite: H (3.395, 0.7929, 0.246) [0.6084, 0.1446, 0.03725]
 PeriodicSite: H (-0.2419, 2.32, 0.3047) [0.1733, 0.4231, 0.04614]
 PeriodicSite: H (2.826, 2.619, 1.502) [0.6851, 0.4775, 0.2275]
 PeriodicSite: H (5.496, 0.5895, 3.986) [0.9216, 0.1075, 0.6036]
 PeriodicSite: H (1.116, 0.3201, 0.266) [0.2054, 0.05837, 0.04029]
 PeriodicSite: H (2.371, 1.049, 2.397) [0.4701, 0.1913, 0.3629]
 PeriodicSite: H (0.1526, 4.11, 2.184) [0.3988, 0.7494, 0.3307]
 PeriodicSite: H (2.168, 4.776, 0.008604) [0.7778, 0.8709, 0.001303],
 'c436bbf4_9aef_44a8_8960_00227f79a32f': Structure Summary
 Lattice
     abc : 4.403401374816899 4.962053775787357 5.689428329467773
  angles : 90.00000250447805 90.00000250447815 90.00000250447816
  volume : 124.31352208745227
       A : 4.4034013748168945 0.0 -1.924787937923611e-07
       B : -2.1689827722570944e-07 4.962053775787348 -2.1689825757675862e-07
       C : 0.0 0.0 5.689428329467773
     pbc : True True True
 PeriodicSite: V (2.02, 2.481, 1.451) [0.4587, 0.5, 0.2551]
 PeriodicSite: V (2.02, 4.962, 4.238) [0.4587, 1.0, 0.7449]
 PeriodicSite: V (2.02, 2.481, 4.238) [0.4587, 0.5, 0.7449]
 PeriodicSite: V (2.02, 2.07e-06, 1.451) [0.4587, 4.172e-07, 0.2551]
 PeriodicSite: V (4.251, 2.481, 2.845) [0.9654, 0.5, 0.5]
 PeriodicSite: V (4.251, 0.0, 2.845) [0.9654, 0.0, 0.5]
 PeriodicSite: V (4.243, 2.481, -2.939e-07) [0.9636, 0.5, 0.0]
 PeriodicSite: V (4.243, 0.0, -1.855e-07) [0.9636, 0.0, 0.0]
 PeriodicSite: H (2.522, 1.9, 2.592) [0.5727, 0.3828, 0.4555]
 PeriodicSite: H (0.7042, 3.341, 4.811) [0.1599, 0.6734, 0.8457]
 PeriodicSite: H (1.551, 0.6233, 3.259) [0.3523, 0.1256, 0.5728]
 PeriodicSite: H (0.4838, 4.28, 1.176) [0.1099, 0.8626, 0.2067]
 PeriodicSite: H (3.972, 0.5121, 4.549) [0.902, 0.1032, 0.7995]
 PeriodicSite: H (3.513, 1.376, 0.883) [0.7977, 0.2773, 0.1552]}

## Relax structures

In [15]:
from xtalpaint.utils.relaxation_utils import relax_structures

In [16]:
relax_kwargs = inputs.relaxation.relax_config.params.model_dump()
print(json.dumps(relax_kwargs, indent=4))

structure_labels, inpainted_structures = map(
    list,
    zip(
        *inpainting_outputs["structures"].get_structures(strct_type="pymatgen").items()
    ),
)

if inputs.relaxation.constrained:
    constrained_relaxation_outputs = relax_structures(
        structures=inpainted_structures,
        **relax_kwargs,
    )
if inputs.relaxation.full:
    relax_kwargs.pop("elements_to_relax", None)
    full_relaxation_outputs = relax_structures(
        structures=inpainted_structures,
        **relax_kwargs,
    )

constrained_relaxation_structures = dict(
    zip(structure_labels, constrained_relaxation_outputs[0])
)

full_relaxation_structures = dict(
    zip(structure_labels, full_relaxation_outputs[0])
)

{
    "mlip": "mattersim",
    "optimizer": "BFGS",
    "load_path": "MatterSim-v1.0.0-5M.pth",
    "fmax": 0.01,
    "max_n_steps": 50,
    "max_natoms_per_batch": 5000,
    "device": "cpu",
    "filter": "none",
    "elements_to_relax": [
        "H"
    ],
    "return_initial_energies": false,
    "return_initial_forces": false,
    "return_final_forces": false
}
2026-06-13 07:54:57.830 | INFO     | mattersim.forcefield.potential:from_checkpoint:891 - Loading the pre-trained mattersim-v1.0.0-5M.pth model

/Users/treents/project/paper-missing-hydrogen-archive/git/XtalPaint-dev/.venv/lib/python3.10/site-packages/mattersim/forcefield/potential.py:896: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(load_path, map_location=device)
  0%|          | 0/5 [00:00<?, ?it/s]

      Step     Time          Energy          fmax
BFGS:    0 07:54:58      -57.106628        9.600606
BFGS:    1 07:54:58      -58.955498        4.820834
BFGS:    2 07:54:58      -61.537964        3.862413
BFGS:    3 07:54:59      -63.260548       10.404643
BFGS:    4 07:54:59      -65.238808        7.416342
BFGS:    5 07:54:59      -67.410065        5.298187
BFGS:    6 07:55:00      -69.316711        6.397086
BFGS:    7 07:55:00      -70.363808        4.018170
BFGS:    8 07:55:00      -71.527634        4.922048
BFGS:    9 07:55:00      -72.753021        5.241137
BFGS:   10 07:55:01      -73.842941        4.774830
BFGS:   11 07:55:01      -74.661278        4.420670
BFGS:   12 07:55:01      -75.007996        2.293677
BFGS:   13 07:55:02      -75.302666        1.313990
BFGS:   14 07:55:02      -75.743782        1.480303
BFGS:   15 07:55:02      -75.925797        1.394388
BFGS:   16 07:55:02      -76.116165        0.899271
BFGS:   17 07:55:03      -76.207062        0.763480
BFGS:   18 07:55:03      -76.262665        0.745936
BFGS:   19 07:55:03      -76.315140        0.887853
BFGS:   20 07:55:04      -76.376366        0.778226
BFGS:   21 07:55:04      -76.428574        0.652225
BFGS:   22 07:55:04      -76.488525        0.648776
BFGS:   23 07:55:04      -76.565445        0.886260
BFGS:   24 07:55:05      -76.667809        1.210744
BFGS:   25 07:55:05      -76.776314        1.232161
BFGS:   26 07:55:05      -76.853424        0.823287
BFGS:   27 07:55:06      -76.899796        0.539274
BFGS:   28 07:55:06      -76.921738        0.407809
BFGS:   29 07:55:06      -76.931107        0.530557
BFGS:   30 07:55:07      -76.946182        0.391963
BFGS:   31 07:55:07      -76.956291        0.270380
BFGS:   32 07:55:07      -76.968697        0.221160
BFGS:   33 07:55:07      -76.974197        0.237598

  0%|          | 0/5 [00:10<?, ?it/s]

BFGS:   34 07:55:08      -76.983131        0.287483
BFGS:   35 07:55:08      -76.992889        0.360731
BFGS:   36 07:55:08      -77.009979        0.495293
BFGS:   37 07:55:09      -77.032516        0.458635
BFGS:   38 07:55:09      -77.051361        0.540976
BFGS:   39 07:55:09      -77.065422        0.593978
BFGS:   40 07:55:09      -77.079414        0.426531
BFGS:   41 07:55:10      -77.102493        0.450735
BFGS:   42 07:55:10      -77.123108        0.461995
BFGS:   43 07:55:10      -77.153549        0.619473
BFGS:   44 07:55:11      -77.168198        0.368640
BFGS:   45 07:55:11      -77.179665        0.424644
BFGS:   46 07:55:11      -77.186089        0.305975
BFGS:   47 07:55:12      -77.192154        0.230333
BFGS:   48 07:55:12      -77.206764        0.288402
BFGS:   49 07:55:12      -77.214516        0.208715
BFGS:   50 07:55:12      -77.217850        0.116398

 20%|██        | 1/5 [00:14<00:59, 14.97s/it]

      Step     Time          Energy          fmax
BFGS:    0 07:55:13      -45.721497        5.455252
BFGS:    1 07:55:13      -47.025089        5.451613
BFGS:    2 07:55:13      -49.607384        3.388715
BFGS:    3 07:55:14      -49.898880        8.097406
BFGS:    4 07:55:14      -50.880714        4.072916
BFGS:    5 07:55:14      -52.005302        4.554719
BFGS:    6 07:55:14      -53.541424        3.706657
BFGS:    7 07:55:14      -54.168583        3.342492
BFGS:    8 07:55:15      -54.534988        2.689680
BFGS:    9 07:55:15      -55.238083        3.393478
BFGS:   10 07:55:15      -55.622288        3.543664
BFGS:   11 07:55:15      -56.468742        3.343932
BFGS:   12 07:55:16      -56.742905        4.085183
BFGS:   13 07:55:16      -56.881660        3.220973
BFGS:   14 07:55:16      -56.966236        2.588984
BFGS:   15 07:55:16      -57.119812        1.276223
BFGS:   16 07:55:17      -57.161217        0.857379
BFGS:   17 07:55:17      -57.216587        0.786497
BFGS:   18 07:55:17      -57.300453        1.380659
BFGS:   19 07:55:17      -57.377090        1.580535
BFGS:   20 07:55:18      -57.539402        2.273654
BFGS:   21 07:55:18      -57.701214        2.089380
BFGS:   22 07:55:18      -57.920460        1.963954
BFGS:   23 07:55:18      -58.088543        1.898226
BFGS:   24 07:55:19      -58.319714        1.670122
BFGS:   25 07:55:19      -58.398998        2.776528
BFGS:   26 07:55:19      -58.527676        1.810123
BFGS:   27 07:55:19      -58.592403        0.879718
BFGS:   28 07:55:19      -58.623924        0.721341
BFGS:   29 07:55:20      -58.656876        0.623261
BFGS:   30 07:55:20      -58.688152        0.716050
BFGS:   31 07:55:20      -58.735966        0.719269
BFGS:   32 07:55:20      -58.771748        0.598627
BFGS:   33 07:55:20      -58.799923        0.518151
BFGS:   34 07:55:21      -58.820461        0.502349
BFGS:   35 07:55:21      -58.845028        0.530628
BFGS:   36 07:55:21      -58.874752        0.631751
BFGS:   37 07:55:21      -58.905205        0.653189
BFGS:   38 07:55:22      -58.934616        0.588979
BFGS:   39 07:55:22      -58.970058        0.660151
BFGS:   40 07:55:22      -59.021484        0.867704
BFGS:   41 07:55:22      -59.092155        1.088671
BFGS:   42 07:55:22      -59.153782        1.766993
BFGS:   43 07:55:23      -59.141834        1.771634
BFGS:   44 07:55:23      -59.347534        0.910544
BFGS:   45 07:55:23      -59.421543        0.555903
BFGS:   46 07:55:23      -59.473049        0.538465
BFGS:   47 07:55:23      -59.490761        0.467302
BFGS:   48 07:55:23      -59.510796        0.388621
BFGS:   49 07:55:24      -59.521786        0.359157
BFGS:   50 07:55:24      -59.528877        0.248143

 40%|████      | 2/5 [00:26<00:38, 12.90s/it]

      Step     Time          Energy          fmax
BFGS:    0 07:55:24      -58.001968       11.424283
BFGS:    1 07:55:24      -59.720779        4.343920
BFGS:    2 07:55:24      -60.901604        3.785213
BFGS:    3 07:55:24      -61.380192        5.791541
BFGS:    4 07:55:24      -61.865456        2.426537
BFGS:    5 07:55:25      -62.345360        2.253572
BFGS:    6 07:55:25      -63.216846        1.770600
BFGS:    7 07:55:25      -63.721439        2.307153
BFGS:    8 07:55:25      -64.053879        2.028067
BFGS:    9 07:55:25      -64.365425        2.534996
BFGS:   10 07:55:25      -64.863464        3.966476
BFGS:   11 07:55:25      -65.281288        4.724015
BFGS:   12 07:55:26      -65.694756        5.130046
BFGS:   13 07:55:26      -66.304909        3.700013
BFGS:   14 07:55:26      -66.661003        2.026453
BFGS:   15 07:55:26      -66.750740        1.867071
BFGS:   16 07:55:26      -66.864456        0.936222
BFGS:   17 07:55:26      -66.899429        0.656410
BFGS:   18 07:55:27      -66.915611        0.601204
BFGS:   19 07:55:27      -66.929382        0.472499
BFGS:   20 07:55:27      -66.949219        0.625538
BFGS:   21 07:55:27      -66.975456        0.578455
BFGS:   22 07:55:27      -66.998596        0.461819
BFGS:   23 07:55:27      -67.010353        0.319910
BFGS:   24 07:55:28      -67.013695        0.156567
BFGS:   25 07:55:28      -67.015572        0.125924
BFGS:   26 07:55:28      -67.018364        0.171066
BFGS:   27 07:55:28      -67.021172        0.179932
BFGS:   28 07:55:29      -67.024231        0.192103
BFGS:   29 07:55:29      -67.026901        0.168849
BFGS:   30 07:55:29      -67.029770        0.182881
BFGS:   31 07:55:29      -67.035057        0.283505
BFGS:   32 07:55:29      -67.047485        0.472710
BFGS:   33 07:55:29      -67.065811        0.675456
BFGS:   34 07:55:30      -67.090622        0.716892
BFGS:   35 07:55:30      -67.125771        0.502650
BFGS:   36 07:55:30      -67.139626        0.463386
BFGS:   37 07:55:30      -67.158684        0.597682
BFGS:   38 07:55:30      -67.164955        1.112185
BFGS:   39 07:55:31      -67.187149        0.576767
BFGS:   40 07:55:31      -67.206337        0.383404
BFGS:   41 07:55:31      -67.224991        0.347981
BFGS:   42 07:55:31      -67.232552        0.361164
BFGS:   43 07:55:31      -67.238098        0.211487
BFGS:   44 07:55:31      -67.246086        0.284183
BFGS:   45 07:55:32      -67.255562        0.234500
BFGS:   46 07:55:32      -67.261742        0.327417
BFGS:   47 07:55:32      -67.265785        0.228334
BFGS:   48 07:55:32      -67.269493        0.136269
BFGS:   49 07:55:32      -67.270500        0.115890
BFGS:   50 07:55:32      -67.271400        0.081513

 60%|██████    | 3/5 [00:34<00:21, 10.86s/it]

      Step     Time          Energy          fmax
BFGS:    0 07:55:33      -84.457382       39.090040
BFGS:    1 07:55:33      -91.134293       18.509986
BFGS:    2 07:55:33      -96.564079        8.247469
BFGS:    3 07:55:34     -100.043640        3.869740
BFGS:    4 07:55:34     -101.831017        1.593755
BFGS:    5 07:55:34     -102.509666        1.941343
BFGS:    6 07:55:34     -102.933533        2.358639
BFGS:    7 07:55:35     -103.625137        3.638950
BFGS:    8 07:55:35     -104.396744        3.730073
BFGS:    9 07:55:35     -105.242958        2.670591
BFGS:   10 07:55:36     -105.938805        2.475998
BFGS:   11 07:55:36     -106.574524        2.241460
BFGS:   12 07:55:36     -107.185867        3.357777
BFGS:   13 07:55:37     -107.944672        3.363956
BFGS:   14 07:55:37     -108.616600        2.116958
BFGS:   15 07:55:37     -108.928017        1.100614
BFGS:   16 07:55:38     -109.143471        1.039524
BFGS:   17 07:55:38     -109.389870        1.040644
BFGS:   18 07:55:38     -109.751030        1.030579
BFGS:   19 07:55:39     -110.087402        1.269077
BFGS:   20 07:55:39     -110.347443        1.434032
BFGS:   21 07:55:39     -110.562889        1.308269
BFGS:   22 07:55:40     -110.760139        1.306999
BFGS:   23 07:55:40     -111.014450        1.303195
BFGS:   24 07:55:40     -111.312729        0.906984
BFGS:   25 07:55:41     -111.584999        0.769049
BFGS:   26 07:55:41     -111.721123        0.692343
BFGS:   27 07:55:41     -111.767853        0.808835
BFGS:   28 07:55:42     -111.875046        0.873471
BFGS:   29 07:55:42     -111.989212        0.617256
BFGS:   30 07:55:42     -112.089355        0.466259
BFGS:   31 07:55:43     -112.152603        0.454279
BFGS:   32 07:55:43     -112.179390        0.469773
BFGS:   33 07:55:43     -112.206688        0.537742
BFGS:   34 07:55:43     -112.270981        0.583350
BFGS:   35 07:55:44     -112.357040        0.511989
BFGS:   36 07:55:44     -112.419144        0.383938
BFGS:   37 07:55:44     -112.452751        0.383180
BFGS:   38 07:55:45     -112.468750        0.380989
BFGS:   39 07:55:45     -112.496338        0.384764
BFGS:   40 07:55:45     -112.544083        0.401306
BFGS:   41 07:55:46     -112.600952        0.404633
BFGS:   42 07:55:46     -112.637970        0.368782
BFGS:   43 07:55:46     -112.655685        0.322971
BFGS:   44 07:55:47     -112.666145        0.288625
BFGS:   45 07:55:47     -112.685562        0.237316
BFGS:   46 07:55:47     -112.707458        0.196239
BFGS:   47 07:55:48     -112.721046        0.181431
BFGS:   48 07:55:48     -112.725815        0.176077
BFGS:   49 07:55:48     -112.728493        0.159717
BFGS:   50 07:55:49     -112.732590        0.147970

 80%|████████  | 4/5 [00:51<00:13, 13.03s/it]

      Step     Time          Energy          fmax
BFGS:    0 07:55:49      -82.259567       10.602653
BFGS:    1 07:55:49      -85.306816        5.309357
BFGS:    2 07:55:49      -87.245369        2.167575
BFGS:    3 07:55:50      -88.064522        1.832354
BFGS:    4 07:55:50      -88.484779        1.745588
BFGS:    5 07:55:50      -88.708374        1.428303
BFGS:    6 07:55:51      -88.832085        1.155568
BFGS:    7 07:55:51      -88.947372        0.954014
BFGS:    8 07:55:51      -89.095680        0.705171
BFGS:    9 07:55:51      -89.208099        0.453120
BFGS:   10 07:55:52      -89.242172        0.362594
BFGS:   11 07:55:52      -89.251686        0.395717
BFGS:   12 07:55:52      -89.268448        0.411105
BFGS:   13 07:55:53      -89.297241        0.364351
BFGS:   14 07:55:53      -89.326584        0.331492
BFGS:   15 07:55:53      -89.345131        0.331487
BFGS:   16 07:55:53      -89.356209        0.356037
BFGS:   17 07:55:54      -89.361847        0.301789
BFGS:   18 07:55:54      -89.368965        0.211932
BFGS:   19 07:55:54      -89.375763        0.178324
BFGS:   20 07:55:55      -89.378693        0.119540
BFGS:   21 07:55:55      -89.379440        0.096656
BFGS:   22 07:55:55      -89.379967        0.085084
BFGS:   23 07:55:55      -89.380814        0.067762
BFGS:   24 07:55:56      -89.381638        0.049268
BFGS:   25 07:55:56      -89.382057        0.038658
BFGS:   26 07:55:56      -89.382195        0.038069
BFGS:   27 07:55:57      -89.382286        0.039582
BFGS:   28 07:55:57      -89.382507        0.045339
BFGS:   29 07:55:57      -89.383018        0.059931
BFGS:   30 07:55:57      -89.384117        0.089551
BFGS:   31 07:55:58      -89.386032        0.131345
BFGS:   32 07:55:58      -89.388390        0.152235
BFGS:   33 07:55:58      -89.390709        0.156422
BFGS:   34 07:55:58      -89.392967        0.168200
BFGS:   35 07:55:59      -89.395920        0.200490
BFGS:   36 07:55:59      -89.406029        0.281892
BFGS:   37 07:55:59      -89.415543        0.263814
BFGS:   38 07:56:00      -89.424110        0.215177
BFGS:   39 07:56:00      -89.425507        0.145314
BFGS:   40 07:56:00      -89.428711        0.165830
BFGS:   41 07:56:00      -89.429932        0.167300
BFGS:   42 07:56:01      -89.434204        0.139631
BFGS:   43 07:56:01      -89.437767        0.088299
BFGS:   44 07:56:01      -89.439545        0.066802
BFGS:   45 07:56:02      -89.439964        0.058844
BFGS:   46 07:56:02      -89.440155        0.053828
BFGS:   47 07:56:02      -89.440598        0.047925
BFGS:   48 07:56:02      -89.441223        0.044422
BFGS:   49 07:56:03      -89.441795        0.043891
BFGS:   50 07:56:03      -89.442131        0.052225

100%|██████████| 5/5 [01:05<00:00, 13.06s/it]

2026-06-13 07:56:03.235 | INFO     | mattersim.forcefield.potential:from_checkpoint:891 - Loading the pre-trained mattersim-v1.0.0-5M.pth model

  0%|          | 0/5 [00:00<?, ?it/s]

      Step     Time          Energy          fmax
BFGS:    0 07:56:03      -57.106628       14.386489
BFGS:    1 07:56:03      -60.530781        7.698420
BFGS:    2 07:56:04      -63.842815        5.753991
BFGS:    3 07:56:04      -65.736717       12.204407
BFGS:    4 07:56:04      -67.891174       11.945297
BFGS:    5 07:56:05      -70.134865        3.913590
BFGS:    6 07:56:05      -71.006340        4.532473
BFGS:    7 07:56:05      -72.511314        6.072092
BFGS:    8 07:56:06      -73.479630        6.725395
BFGS:    9 07:56:06      -74.266739        3.383750
BFGS:   10 07:56:06      -74.891846        2.290793
BFGS:   11 07:56:06      -75.470016        2.003532
BFGS:   12 07:56:07      -75.981743        2.209775
BFGS:   13 07:56:07      -76.235359        4.015708
BFGS:   14 07:56:07      -76.515366        1.350947
BFGS:   15 07:56:08      -76.639320        0.694824
BFGS:   16 07:56:08      -76.732834        1.031189
BFGS:   17 07:56:08      -76.787010        0.928270
BFGS:   18 07:56:09      -76.863647        0.935893
BFGS:   19 07:56:09      -76.926018        0.963225
BFGS:   20 07:56:09      -77.038445        1.851333
BFGS:   21 07:56:09      -77.181313        2.344670
BFGS:   22 07:56:10      -77.352364        1.618359
BFGS:   23 07:56:10      -77.457817        0.668515
BFGS:   24 07:56:10      -77.501633        0.576883
BFGS:   25 07:56:11      -77.588181        0.929002
BFGS:   26 07:56:11      -77.725922        2.059755
BFGS:   27 07:56:11      -77.533501        4.650868
BFGS:   28 07:56:12      -77.670143        3.991071
BFGS:   29 07:56:12      -77.805916        2.013556
BFGS:   30 07:56:12      -78.001137        1.609624
BFGS:   31 07:56:12      -78.100159        1.516192
BFGS:   32 07:56:13      -78.171059        1.031646
BFGS:   33 07:56:13      -78.297089        1.131156
BFGS:   34 07:56:13      -78.341454        1.113095
BFGS:   35 07:56:14      -78.388977        0.788060
BFGS:   36 07:56:14      -78.487320        0.693306
BFGS:   37 07:56:14      -78.520576        0.707849
BFGS:   38 07:56:14      -78.553406        0.452791
BFGS:   39 07:56:15      -78.570740        0.350170
BFGS:   40 07:56:15      -78.585960        0.312525
BFGS:   41 07:56:15      -78.596909        0.294577
BFGS:   42 07:56:16      -78.607498        0.315432
BFGS:   43 07:56:16      -78.621712        0.360194
BFGS:   44 07:56:16      -78.645126        0.466469
BFGS:   45 07:56:16      -78.679459        0.569241
BFGS:   46 07:56:17      -78.719261        0.583011
BFGS:   47 07:56:17      -78.749016        0.471591
BFGS:   48 07:56:17      -78.766548        0.431714

  0%|          | 0/5 [00:14<?, ?it/s]

BFGS:   49 07:56:18      -78.783127        0.395422
BFGS:   50 07:56:18      -78.794312        0.415547

 20%|██        | 1/5 [00:15<01:00, 15.23s/it]

      Step     Time          Energy          fmax
BFGS:    0 07:56:18      -45.721497        5.455252
BFGS:    1 07:56:19      -47.615005        5.120204
BFGS:    2 07:56:19      -48.957989       15.743132
BFGS:    3 07:56:19      -50.295048        4.509679
BFGS:    4 07:56:19      -51.705784        4.906157
BFGS:    5 07:56:20      -53.247025        6.828655
BFGS:    6 07:56:20      -54.218452        3.476381
BFGS:    7 07:56:20      -55.474419        3.779168
BFGS:    8 07:56:21      -56.217415        3.965616
BFGS:    9 07:56:21      -56.686558        9.077760
BFGS:   10 07:56:21      -57.230209        3.107448
BFGS:   11 07:56:21      -57.565346        2.358569
BFGS:   12 07:56:22      -57.955189        1.797454
BFGS:   13 07:56:22      -58.062511        1.386323
BFGS:   14 07:56:22      -58.312115        1.056514
BFGS:   15 07:56:22      -58.454342        1.136189
BFGS:   16 07:56:23      -58.559692        0.850588
BFGS:   17 07:56:23      -58.630520        0.973984
BFGS:   18 07:56:23      -58.707504        1.216874
BFGS:   19 07:56:24      -58.810528        1.330686
BFGS:   20 07:56:24      -58.883755        1.141242
BFGS:   21 07:56:24      -58.948597        0.739761
BFGS:   22 07:56:24      -59.003944        0.778941
BFGS:   23 07:56:24      -59.033627        0.822475
BFGS:   24 07:56:25      -59.073074        0.539226
BFGS:   25 07:56:25      -59.141205        0.713767
BFGS:   26 07:56:25      -59.182091        0.606859
BFGS:   27 07:56:25      -59.253773        0.779980
BFGS:   28 07:56:25      -59.316902        0.915124
BFGS:   29 07:56:26      -59.376129        0.800837
BFGS:   30 07:56:26      -59.426987        0.630665
BFGS:   31 07:56:26      -59.451248        0.401173
BFGS:   32 07:56:27      -59.460011        0.258582
BFGS:   33 07:56:27      -59.465328        0.272481
BFGS:   34 07:56:27      -59.473034        0.198015
BFGS:   35 07:56:27      -59.476383        0.155925
BFGS:   36 07:56:28      -59.478191        0.105306
BFGS:   37 07:56:28      -59.479805        0.118407
BFGS:   38 07:56:28      -59.482422        0.129557
BFGS:   39 07:56:28      -59.485428        0.174573
BFGS:   40 07:56:28      -59.487820        0.170393
BFGS:   41 07:56:28      -59.489182        0.109339
BFGS:   42 07:56:29      -59.490150        0.112341
BFGS:   43 07:56:29      -59.491192        0.088350
BFGS:   44 07:56:29      -59.492374        0.117280
BFGS:   45 07:56:29      -59.493702        0.143901
BFGS:   46 07:56:29      -59.495342        0.146498
BFGS:   47 07:56:30      -59.497528        0.155938
BFGS:   48 07:56:30      -59.500107        0.146664
BFGS:   49 07:56:30      -59.502525        0.127810
BFGS:   50 07:56:30      -59.504631        0.126309

 40%|████      | 2/5 [00:27<00:40, 13.36s/it]

      Step     Time          Energy          fmax
BFGS:    0 07:56:30      -58.001968       13.017150
BFGS:    1 07:56:30      -60.253036        3.870456
BFGS:    2 07:56:30      -61.533497        3.705069
BFGS:    3 07:56:31      -62.973255        6.357388
BFGS:    4 07:56:31      -64.365280        4.387346
BFGS:    5 07:56:31      -65.101280        2.756728
BFGS:    6 07:56:31      -65.623199        3.615154
BFGS:    7 07:56:31      -66.234741        3.574900
BFGS:    8 07:56:31      -66.059929       11.423292
BFGS:    9 07:56:31      -66.943382        2.801358
BFGS:   10 07:56:32      -67.122528        2.013614
BFGS:   11 07:56:32      -67.215195        0.653441
BFGS:   12 07:56:32      -67.241577        0.746932
BFGS:   13 07:56:32      -67.261543        0.387926
BFGS:   14 07:56:32      -67.270157        0.323310
BFGS:   15 07:56:32      -67.281586        0.453158
BFGS:   16 07:56:32      -67.292206        0.513113
BFGS:   17 07:56:33      -67.305046        0.446508
BFGS:   18 07:56:33      -67.318024        0.387116
BFGS:   19 07:56:33      -67.331299        0.426052
BFGS:   20 07:56:33      -67.347672        0.500392
BFGS:   21 07:56:33      -67.366547        0.645757
BFGS:   22 07:56:33      -67.382080        0.607774
BFGS:   23 07:56:33      -67.395180        0.513125
BFGS:   24 07:56:34      -67.412964        0.521820
BFGS:   25 07:56:34      -67.430107        0.610412
BFGS:   26 07:56:34      -67.441132        0.328102
BFGS:   27 07:56:34      -67.445938        0.218632
BFGS:   28 07:56:34      -67.450027        0.335173
BFGS:   29 07:56:34      -67.457062        0.373415
BFGS:   30 07:56:35      -67.485977        0.389468
BFGS:   31 07:56:35      -67.493980        0.255472
BFGS:   32 07:56:35      -67.512360        0.495296
BFGS:   33 07:56:35      -67.530556        0.639412
BFGS:   34 07:56:35      -67.546555        0.436994
BFGS:   35 07:56:35      -67.559685        0.741939
BFGS:   36 07:56:35      -67.577324        0.521910
BFGS:   37 07:56:36      -67.613228        0.560569
BFGS:   38 07:56:36      -67.626297        0.395653
BFGS:   39 07:56:36      -67.639771        0.310300
BFGS:   40 07:56:36      -67.645935        0.232910
BFGS:   41 07:56:36      -67.654045        0.280918
BFGS:   42 07:56:37      -67.662743        0.350401
BFGS:   43 07:56:37      -67.671028        0.365654
BFGS:   44 07:56:37      -67.682007        0.446937
BFGS:   45 07:56:37      -67.693810        0.343172
BFGS:   46 07:56:37      -67.717751        0.387426
BFGS:   47 07:56:38      -67.738373        0.567738
BFGS:   48 07:56:38      -67.768639        0.745192
BFGS:   49 07:56:38      -67.805252        0.744478
BFGS:   50 07:56:38      -67.838043        0.555598

 60%|██████    | 3/5 [00:35<00:21, 10.86s/it]

      Step     Time          Energy          fmax
BFGS:    0 07:56:38      -84.457382       41.158449
BFGS:    1 07:56:39      -94.149696       10.244834
BFGS:    2 07:56:39      -98.496895        5.262557
BFGS:    3 07:56:39     -101.959831        2.506469
BFGS:    4 07:56:40     -103.111946        2.183027
BFGS:    5 07:56:40     -104.118851        2.267829
BFGS:    6 07:56:40     -105.009689        2.138301
BFGS:    7 07:56:41     -105.801437        1.953427
BFGS:    8 07:56:41     -106.617714        2.108026
BFGS:    9 07:56:41     -107.155930        1.880905
BFGS:   10 07:56:41     -107.439781        1.624135
BFGS:   11 07:56:42     -107.956276        1.623929
BFGS:   12 07:56:42     -108.484650        1.579771
BFGS:   13 07:56:42     -108.838646        1.373115
BFGS:   14 07:56:43     -109.090942        1.233460
BFGS:   15 07:56:43     -109.312561        1.136920
BFGS:   16 07:56:43     -109.492584        0.855552
BFGS:   17 07:56:44     -109.639961        0.826632
BFGS:   18 07:56:44     -109.742615        0.852720
BFGS:   19 07:56:44     -109.840225        0.959697
BFGS:   20 07:56:44     -109.965492        0.934163
BFGS:   21 07:56:45     -110.067261        0.684834
BFGS:   22 07:56:45     -110.136497        0.693813
BFGS:   23 07:56:45     -110.200722        0.590011
BFGS:   24 07:56:46     -110.260445        0.621170
BFGS:   25 07:56:46     -110.318909        0.733022
BFGS:   26 07:56:46     -110.385086        0.764738
BFGS:   27 07:56:47     -110.426186        0.448288
BFGS:   28 07:56:47     -110.453903        0.366973
BFGS:   29 07:56:47     -110.486214        0.341626
BFGS:   30 07:56:48     -110.516922        0.515340
BFGS:   31 07:56:48     -110.543694        0.542109
BFGS:   32 07:56:48     -110.574043        0.435814
BFGS:   33 07:56:49     -110.606903        0.372819
BFGS:   34 07:56:49     -110.627754        0.281445
BFGS:   35 07:56:49     -110.640671        0.322245
BFGS:   36 07:56:50     -110.653282        0.259143
BFGS:   37 07:56:50     -110.662300        0.193561
BFGS:   38 07:56:50     -110.671806        0.212824
BFGS:   39 07:56:51     -110.679230        0.221678
BFGS:   40 07:56:51     -110.685760        0.194357
BFGS:   41 07:56:51     -110.692459        0.145765
BFGS:   42 07:56:51     -110.698166        0.130910
BFGS:   43 07:56:52     -110.701782        0.126928
BFGS:   44 07:56:52     -110.704575        0.115622
BFGS:   45 07:56:52     -110.707657        0.108557
BFGS:   46 07:56:53     -110.710922        0.085534
BFGS:   47 07:56:53     -110.713257        0.081363
BFGS:   48 07:56:53     -110.714684        0.089454
BFGS:   49 07:56:54     -110.715996        0.086997
BFGS:   50 07:56:54     -110.718010        0.089682

 80%|████████  | 4/5 [00:51<00:12, 12.91s/it]

      Step     Time          Energy          fmax
BFGS:    0 07:56:54      -82.259567       11.421439
BFGS:    1 07:56:55      -86.444031        4.356897
BFGS:    2 07:56:55      -87.669884        2.747404
BFGS:    3 07:56:55      -88.713028        1.499375
BFGS:    4 07:56:55      -89.121529        1.124942
BFGS:    5 07:56:56      -89.333771        1.171344
BFGS:    6 07:56:56      -89.589943        1.198057
BFGS:    7 07:56:56      -89.984161        1.507533
BFGS:    8 07:56:57      -90.322853        1.699763
BFGS:    9 07:56:57      -90.707260        1.258113
BFGS:   10 07:56:57      -90.956215        1.620046
BFGS:   11 07:56:57      -91.229355        1.776993
BFGS:   12 07:56:58      -91.800339        1.611244
BFGS:   13 07:56:58      -92.075539        1.609706
BFGS:   14 07:56:58      -92.363174        1.328576
BFGS:   15 07:56:59      -92.514008        0.995119
BFGS:   16 07:56:59      -92.703316        0.975937
BFGS:   17 07:56:59      -92.792717        0.940180
BFGS:   18 07:56:59      -92.850174        0.735165
BFGS:   19 07:57:00      -92.920349        0.654592
BFGS:   20 07:57:00      -93.001266        0.759645
BFGS:   21 07:57:00      -93.096008        1.177526
BFGS:   22 07:57:01      -93.193420        1.205582
BFGS:   23 07:57:01      -93.276047        0.873818
BFGS:   24 07:57:01      -93.372498        0.451984
BFGS:   25 07:57:01      -93.401009        0.473402
BFGS:   26 07:57:02      -93.427521        0.396981
BFGS:   27 07:57:02      -93.450081        0.310292
BFGS:   28 07:57:02      -93.467239        0.222415
BFGS:   29 07:57:03      -93.476723        0.214387
BFGS:   30 07:57:03      -93.484169        0.203356
BFGS:   31 07:57:03      -93.492210        0.225861
BFGS:   32 07:57:04      -93.502922        0.298493
BFGS:   33 07:57:04      -93.515480        0.392124
BFGS:   34 07:57:04      -93.531723        0.550117
BFGS:   35 07:57:04      -93.552887        0.603176
BFGS:   36 07:57:05      -93.579727        0.520311
BFGS:   37 07:57:05      -93.622658        0.357141
BFGS:   38 07:57:05      -93.646088        0.379578
BFGS:   39 07:57:05      -93.665215        0.431018
BFGS:   40 07:57:06      -93.678596        0.332025
BFGS:   41 07:57:06      -93.690178        0.176265
BFGS:   42 07:57:06      -93.697586        0.166628
BFGS:   43 07:57:07      -93.702522        0.200603
BFGS:   44 07:57:07      -93.707970        0.197566
BFGS:   45 07:57:07      -93.715233        0.139035
BFGS:   46 07:57:07      -93.720306        0.117252
BFGS:   47 07:57:08      -93.722481        0.103641
BFGS:   48 07:57:08      -93.723602        0.098137
BFGS:   49 07:57:08      -93.724785        0.079994
BFGS:   50 07:57:09      -93.725929        0.065639

100%|██████████| 5/5 [01:05<00:00, 13.16s/it]

## Evaluate the inpainted structures with repspect to the initial reference

In [17]:
from xtalpaint.eval import evaluate_inpainting
import pandas as pd

In [18]:
rmsd_inpainted_structures = evaluate_inpainting(
    inpainted_structures=inpainting_outputs["structures"],
    reference_structures=input_structures,
    metric="rmsd",
    max_workers=3,
    normalization_element='H',
)

matches_inpainted_structures = evaluate_inpainting(
    inpainted_structures=inpainting_outputs["structures"],
    reference_structures=input_structures,
    metric="match",
    max_workers=3,
)

inpainted_evaluation = pd.merge(
    rmsd_inpainted_structures, matches_inpainted_structures, left_index=True, right_index=True
)

rmsd_constrained_relaxation = evaluate_inpainting(
    inpainted_structures=constrained_relaxation_structures,
    reference_structures=input_structures,
    metric="rmsd",
    max_workers=3,
    normalization_element='H',
)
matches_constrained_relaxation = evaluate_inpainting(
    inpainted_structures=constrained_relaxation_structures,
    reference_structures=input_structures,
    metric="match",
    max_workers=3,
)

constrained_relaxation_evaluation = pd.merge(
    rmsd_constrained_relaxation, matches_constrained_relaxation, left_index=True, right_index=True
)

  0%|          | 0/5 [00:00<?, ?it/s]

MODELS_PROJECT_ROOT: /Users/treents/project/paper-missing-hydrogen-archive/git/XtalPaint-dev/.venv/lib/python3.10/site-packages/mattergen

 80%|████████  | 4/5 [00:04<00:01,  1.05s/it]
  0%|          | 0/5 [00:00<?, ?it/s]

MODELS_PROJECT_ROOT: /Users/treents/project/paper-missing-hydrogen-archive/git/XtalPaint-dev/.venv/lib/python3.10/site-packages/mattergen

 80%|████████  | 4/5 [00:03<00:00,  1.22it/s]
  0%|          | 0/5 [00:00<?, ?it/s]

MODELS_PROJECT_ROOT: /Users/treents/project/paper-missing-hydrogen-archive/git/XtalPaint-dev/.venv/lib/python3.10/site-packages/mattergen

 80%|████████  | 4/5 [00:03<00:00,  1.21it/s]
  0%|          | 0/5 [00:00<?, ?it/s]

MODELS_PROJECT_ROOT: /Users/treents/project/paper-missing-hydrogen-archive/git/XtalPaint-dev/.venv/lib/python3.10/site-packages/mattergen

 80%|████████  | 4/5 [00:03<00:00,  1.15it/s]

In [19]:
inpainted_evaluation

                                          rmsd  match
keys
20acc66e_8e38_4e5e_9e7a_c2400262cdc8  1.146412  False
47b9a869_9b1e_438b_8c93_f5ac654bfdd8  1.030685  False
662c7351_ee76_48ea_bab7_b733e1fdf607  1.624403  False
7fa282c5_4971_46f4_8b3b_776595a0fa06  1.225103  False
c436bbf4_9aef_44a8_8960_00227f79a32f  1.199534  False

In [20]:
constrained_relaxation_evaluation

                                          rmsd  match
keys
20acc66e_8e38_4e5e_9e7a_c2400262cdc8  0.870491  False
47b9a869_9b1e_438b_8c93_f5ac654bfdd8  0.026524   True
662c7351_ee76_48ea_bab7_b733e1fdf607  1.741756  False
7fa282c5_4971_46f4_8b3b_776595a0fa06  0.619338  False
c436bbf4_9aef_44a8_8960_00227f79a32f  1.550880  False